# Generated by Django 3.0.3 on 2020-07-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseBy', models.CharField(max_length=50)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('CourseStatus', models.CharField(default='OFF', max_length=2, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Date_PostTest',
            new_name='Date_PostTest1',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Date_PreTest',
            new_name='Date_PreTest1',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Date_Vdo',
            new_name='Date_Vdo1_1',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Score_PostTest',
            new_name='Score_PostTest1',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Score_PreTest',
            new_name='Score_PreTest1',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Vdo_pass',
            new_name='Vdo_pass1_1',
        ),
        migrations.AddField(
            model_name='staff',
            name='Date_Vdo1_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Date_Vdo1_3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Vdo_pass1_2',
            field=models.CharField(default='no', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Vdo_pass1_3',
            field=models.CharField(default='no', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Course_Pretest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestTitle', models.CharField(max_length=300)),
                ('Test1', models.CharField(max_length=200)),
                ('Test2', models.CharField(max_length=200)),
                ('Test3', models.CharField(max_length=200)),
                ('Test4', models.CharField(max_length=200)),
                ('Test_Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='elearning.Course')),
            ],
        ),
    ]
