# Generated by Django 3.0.3 on 2020-07-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20200714_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('ConstructorName', models.CharField(max_length=100)),
                ('ConstructorPosition', models.CharField(max_length=100)),
                ('Document', models.URLField(max_length=300)),
                ('Date_Created', models.DateField(auto_now_add=True, null=True)),
                ('Link_Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Courses', to='elearning.Course')),
            ],
        ),
    ]
