# Generated by Django 3.0.3 on 2020-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_sub_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_course',
            name='URLGdrive',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseStatus',
            field=models.CharField(default='OFF', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course_pretest',
            name='Test1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course_pretest',
            name='Test2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course_pretest',
            name='Test3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course_pretest',
            name='Test4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='ConstructorName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='ConstructorPosition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='Document',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
