# Generated by Django 3.0.3 on 2020-07-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20200715_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_score',
            old_name='Date_Created',
            new_name='Post_Created',
        ),
        migrations.RenameField(
            model_name='staff_score',
            old_name='Score',
            new_name='Post_Score',
        ),
        migrations.RemoveField(
            model_name='staff_score',
            name='Link_SubCourse',
        ),
        migrations.RemoveField(
            model_name='staff_score',
            name='Type',
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Staff_Vdolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateTimeField(null=True)),
                ('Status', models.CharField(default='on Process', max_length=12, null=True)),
                ('Link_SubCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCourse_Vdo', to='elearning.Sub_Course')),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Vdo', to='elearning.Staff')),
            ],
        ),
    ]
