# Generated by Django 3.0.3 on 2020-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_auto_20200715_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_score',
            old_name='Post_Created',
            new_name='Post_Created1',
        ),
        migrations.RenameField(
            model_name='staff_score',
            old_name='Pre_Created',
            new_name='Post_Created10',
        ),
        migrations.RenameField(
            model_name='staff_score',
            old_name='Post_Score',
            new_name='Post_Score1',
        ),
        migrations.RenameField(
            model_name='staff_score',
            old_name='Pre_Score',
            new_name='Post_Score10',
        ),
        migrations.RemoveField(
            model_name='staff_score',
            name='Link_Course',
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created5',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created6',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created7',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created8',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Created9',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Post_Score9',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created10',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created5',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created6',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created7',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created8',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Created9',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score7',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score8',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff_score',
            name='Pre_Score9',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
