# Generated by Django 3.0.3 on 2020-07-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20200715_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_vdolog',
            name='Link_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Vdo', to='elearning.Course'),
        ),
    ]
