# Generated by Django 3.0.3 on 2020-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_sub_course_totaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Couse_Sub_Total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
