# Generated by Django 3.0.3 on 2020-07-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_course_couse_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_course',
            name='Tel',
            field=models.CharField(default='0000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sub_course',
            name='email',
            field=models.EmailField(default='uuu@pea.co.th', max_length=254, null=True),
        ),
    ]
