# Generated by Django 3.0.3 on 2020-07-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_auto_20200716_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_pretest',
            name='Test_ans',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
