# Generated by Django 3.0.3 on 2020-07-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_course_pretest_test_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_pretest',
            name='Test_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
