# Generated by Django 3.0.3 on 2020-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_auto_20200719_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Total_QS',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
