# Generated by Django 3.0.3 on 2020-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_course_course_total_qs'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Pass_Score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
