# Generated by Django 3.0.3 on 2020-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_course_course_pass_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='Error_Detail',
            field=models.TextField(blank=True, default='error', null=True),
        ),
    ]
