# Generated by Django 3.0.3 on 2020-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0017_auto_20200719_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Cover_img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
