# Generated by Django 3.0.3 on 2020-07-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0019_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_1', models.IntegerField(default=0)),
                ('No_2', models.IntegerField(default=0)),
                ('No_3', models.IntegerField(default=0)),
                ('No_4', models.IntegerField(default=0)),
                ('No_5', models.IntegerField(default=0)),
                ('No_6', models.IntegerField(default=0)),
                ('No_7', models.IntegerField(default=0)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.BooleanField(default=False)),
                ('Link_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Eva', to='elearning.Course')),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Eva', to='elearning.Staff')),
            ],
        ),
    ]
