# Generated by Django 3.0.3 on 2020-08-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0020_evaluate_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffID', models.CharField(max_length=10)),
                ('Status', models.BooleanField(default=False)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Link_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Closed', to='elearning.Course')),
            ],
        ),
    ]
