# Generated by Django 3.0.3 on 2020-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0021_closed_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_class',
            name='Status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
