# Generated by Django 3.0.3 on 2020-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0023_auto_20200821_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_class',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
