# Generated by Django 3.0.3 on 2020-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0024_auto_20200821_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate_t',
            name='No_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='No_9',
            field=models.IntegerField(default=0),
        ),
    ]
