# Generated by Django 3.0.3 on 2020-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0025_auto_20200825_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StaffID', models.CharField(max_length=10)),
                ('no1', models.TextField(blank=True, default='ข้อ1', null=True)),
                ('no1_Score', models.IntegerField(default=0, null=True)),
                ('no2_1', models.TextField(blank=True, default='ข้อ2_1', null=True)),
                ('no2_1_Score', models.IntegerField(default=0, null=True)),
                ('no2_2', models.TextField(blank=True, default='ข้อ2_2', null=True)),
                ('no2_2_Score', models.IntegerField(default=0, null=True)),
                ('no2_3', models.TextField(blank=True, default='ข้อ2_3', null=True)),
                ('no2_3_Score', models.IntegerField(default=0, null=True)),
                ('no2_4', models.TextField(blank=True, default='ข้อ2_4', null=True)),
                ('no2_4_Score', models.IntegerField(default=0, null=True)),
                ('no2_5', models.TextField(blank=True, default='ข้อ2_5', null=True)),
                ('no2_5_Score', models.IntegerField(default=0, null=True)),
                ('no3', models.TextField(blank=True, default='ข้อ3', null=True)),
                ('no3_Score', models.IntegerField(default=0, null=True)),
                ('no4', models.TextField(blank=True, default='ข้อ4', null=True)),
                ('no4_Score', models.IntegerField(default=0, null=True)),
                ('no5', models.TextField(blank=True, default='ข้อ5', null=True)),
                ('no5_Score', models.IntegerField(default=0, null=True)),
                ('no6', models.TextField(blank=True, default='ข้อ6', null=True)),
                ('no6_Score', models.IntegerField(default=0, null=True)),
                ('no7', models.TextField(blank=True, default='ข้อ7', null=True)),
                ('no7_Score', models.IntegerField(default=0, null=True)),
                ('no8', models.TextField(blank=True, default='ข้อ8', null=True)),
                ('no8_Score', models.IntegerField(default=0, null=True)),
                ('no9', models.TextField(blank=True, default='ข้อ9', null=True)),
                ('no9_Score', models.IntegerField(default=0, null=True)),
                ('no10', models.TextField(blank=True, default='ข้อ10', null=True)),
                ('no10_Score', models.IntegerField(default=0, null=True)),
                ('Status', models.BooleanField(default=False, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
