# Generated by Django 3.0.3 on 2020-09-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0026_hub_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub_test',
            name='Status',
            field=models.CharField(default=0, max_length=1, null=True),
        ),
    ]
