# Generated by Django 3.0.3 on 2020-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0027_auto_20200915_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bu_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StaffID', models.CharField(max_length=10)),
                ('no1', models.TextField(blank=True, default='ข้อ1', null=True)),
                ('Status', models.CharField(default=0, max_length=1, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
