# Generated by Django 3.0.3 on 2020-09-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0028_bu_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub_test',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hub_test',
            name='StaffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_testihub', to='elearning.Staff'),
        ),
    ]
