# Generated by Django 3.0.3 on 2021-03-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0030_hub_test_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Type',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
