# Generated by Django 3.0.3 on 2021-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0031_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Post_Test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Pre_Test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='Document',
            field=models.URLField(max_length=300),
        ),
    ]
