# Generated by Django 3.0.3 on 2021-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0032_auto_20210312_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate_t',
            name='Future_Subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='Suggestion',
            field=models.TextField(blank=True, default='ข้อเสนอแนะ', null=True),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='Usability',
            field=models.TextField(blank=True, default='การนำไปใช้', null=True),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='Document',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sub_course',
            name='URLGdrive',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
