# Generated by Django 3.0.3 on 2021-03-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0033_auto_20210312_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=300)),
                ('Order', models.CharField(max_length=2)),
                ('Sub_Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Courses', to='elearning.Sub_Course')),
            ],
        ),
    ]
