# Generated by Django 3.0.3 on 2021-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0034_topic_evaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate_t',
            name='Future_Subject',
            field=models.CharField(blank=True, default='หัวข้อที่สนใจ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluate_t',
            name='Usability',
            field=models.CharField(blank=True, default='การนำไปใช้', max_length=300, null=True),
        ),
    ]
