# Generated by Django 3.0.3 on 2021-04-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0035_auto_20210315_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_B1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_B2',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_B3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_B4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_B5',
            field=models.TextField(blank=True, default='ข้อเสนอแนะ', null=True),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Gender',
            field=models.CharField(blank=True, default='-', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Generation',
            field=models.CharField(blank=True, default='Gen', max_length=20, null=True),
        ),
    ]
