# Generated by Django 3.0.3 on 2021-04-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0036_auto_20210429_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluate_t',
            name='KM_B2',
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_DDoc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Leaflets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Meeting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Social',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Training',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_Vdo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluate_t',
            name='KM_email',
            field=models.IntegerField(default=0),
        ),
    ]
